### ISSUE TITLE
Attempt to index a nil value (local 'xTarget')

### ISSUE THREAD

**Issue by Vareska** [Giana/g-givecar#7]
[script:g-givecar] SCRIPT ERROR: @g-givecar/server/main.lua:46: attempt to index a nil value (local 'xTarget')

local xTarget = QBCore.Functions.GetPlayer(id)
local cid = xTarget.PlayerData.citizenid

The second the line is the one throwing the error

**Comment by Giana** [comment]
This would be due to not passing a valid server ID of an online player. If someone uses /id, it will tell them their server ID, and you can use that ID in the command to give them the car. I will update the code to show an error when passed an invalid server ID rather than the script throwing an error.

**Comment by Vareska** [comment]
Nope, I was the only person in the server, my ID was 1 so I used /admingivecar 1 carname and it threw the error

**Comment by Giana** [comment]
I just tested the same scenario and was successful. Check out the new code from master: I just pushed an update which will tell you if you are passing in an invalid server ID, rather than the script throwing this error. Please verify your server ID again before using the command and seeing what happens.

**Comment by Giana** [comment]
It has been a week with no response. Closing this as I could not replicate the issue. Please open an issue if you encounter any more problems in the future. Thank you!
